version: "3.9"

services:
  app:
    container_name: conge-app-prod
    build:
      context: .
      target: runner
    image: conge-app:prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["sh", "-c", "npm run seed && npm run start"]

  mongo:
    image: mongo:7.0
    container_name: conge-mongo-prod
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: conge
    volumes:
      - mongodata:/data/db
      - ./docker/mongo-init-replica.sh:/docker-entrypoint-initdb.d/mongo-init-replica.sh:ro
    restart: unless-stopped

volumes:
  mongodata:
